/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan.jendela.dunia;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MR AL
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomer = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        jenis = new javax.swing.JComboBox<>();
        kembali = new com.toedter.calendar.JDateChooser();
        pinjam = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        kategori = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        tulisan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);
        getContentPane().add(txtNomer);
        txtNomer.setBounds(190, 130, 150, 30);
        getContentPane().add(txtjudul);
        txtjudul.setBounds(190, 250, 150, 30);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buku Pelajaran", "Novel atau Komik", "Buku Bacaan" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(190, 210, 150, 30);
        getContentPane().add(kembali);
        kembali.setBounds(190, 330, 150, 30);
        getContentPane().add(pinjam);
        pinjam.setBounds(190, 290, 150, 30);

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 370, 150, 96);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alamat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 370, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nomer Anggota");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 250, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Buku");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Pinjam");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 290, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Kembali");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 330, 130, 30);
        getContentPane().add(Nama);
        Nama.setBounds(190, 170, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Anggota");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 170, 130, 30);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "Nama", "Jenis", "Judul", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
            tblData.getColumnModel().getColumn(1).setResizable(false);
            tblData.getColumnModel().getColumn(2).setResizable(false);
            tblData.getColumnModel().getColumn(3).setResizable(false);
            tblData.getColumnModel().getColumn(4).setResizable(false);
            tblData.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 210, 900, 430);

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh);
        Refresh.setBounds(50, 530, 310, 30);
        getContentPane().add(status);
        status.setBounds(660, 570, 190, 30);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(50, 490, 90, 30);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(170, 490, 80, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(270, 490, 90, 30);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(50, 570, 310, 30);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(50, 610, 310, 30);

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nomer", "Nama", "Jenis", "Judul" }));
        getContentPane().add(kategori);
        kategori.setBounds(620, 170, 120, 30);
        getContentPane().add(txtsearch);
        txtsearch.setBounds(390, 170, 210, 30);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 170, 120, 30);

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR AL\\Pictures\\sourcepbo\\tsnew.png")); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(50, 20, 120, 90);

        tulisan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tulisan.setForeground(new java.awt.Color(255, 255, 255));
        tulisan.setText("Perpustakaan Telkom");
        getContentPane().add(tulisan);
        tulisan.setBounds(190, 50, 270, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/jendela/dunia/perpus.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, 0, 1380, 730);

        setBounds(0, 0, 1391, 753);
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
     selectData();
    }//GEN-LAST:event_RefreshActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
               if ("".equals(txtNomer.getText()) || "".equals(Alamat.getText())
               || "".equals(jenis.getSelectedItem()) || "".equals(Nama.getText())
                    || "".equals(pinjam.getDate().toString()))
       {
           JOptionPane.showMessageDialog(this, "harap isi data", "Error", JOptionPane.WARNING_MESSAGE);
       }else {
          
            String SQL = "INSERT INTO `tb_buku`(`Nomer`, `Nama`, `Jenis`, `Judul`, `Pinjam`, `Kembali`, `Alamat`, `Status`) VALUES('"+txtNomer.getText()
                    +"','"+Nama.getText()+"','"+jenis.getSelectedItem()+"','"+txtjudul.getText()+"','"+pinjam.getDate().toString()
                    +"','"+kembali.getDate().toString()+"','"+Alamat.getText()+"','"+status.getText()+"')";
          
            int status = KoneksiDB.execute(SQL);
            if (status ==1){
                JOptionPane.showMessageDialog(this, "Data berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               }
       }  
              // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
   int baris = tblData.getSelectedRow();
        if (baris != -1){
            String Nomer = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_buku WHERE Nomer='"+Nomer+"'";
            int status = KoneksiDB.execute(SQL);
            if (status ==1){
               JOptionPane.showMessageDialog(this, "Data berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris data terlebih dahulu", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }selectData();        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        txtNomer.setText("");
        Nama.setText("");
        Alamat.setText("");
        pinjam.setDate(null);
        kembali.setDate(null);
        txtjudul.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       MessageFormat header = new MessageFormat("Data Peminjaman Buku Perpustakaan");
       MessageFormat footer = new MessageFormat("Page (0,number,integer)    ");
       try{
           tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer,true, null, true, null);
           }catch(java.awt.print.PrinterException e){
               System.err.format("Cannot Print %s%n", e.getMessage());
       }
       
    }//GEN-LAST:event_printActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
   if ("".equals(txtNomer.getText()) || "".equals(Alamat.getText())
               || "".equals(jenis.getSelectedItem()) || "".equals(Nama.getText())
                    || "".equals(pinjam.getDate().toString())){
           JOptionPane.showMessageDialog(this, "harap isi data", "Error", JOptionPane.WARNING_MESSAGE);
       }else {
          
            int baris = tblData.getSelectedRow();
            String Nomer = tblData.getValueAt(baris, 0).toString();
           String SQL = "UPDATE `tb_buku` SET `Nomer`='"+txtNomer.getText()+"',`Nama`='"+Nama.getText()
                   +"',`Jenis`='"+jenis.getSelectedItem()+"',`Judul`='"+txtjudul.getText()+"',`Pinjam`='"+pinjam.getDate().toString()
                   +"',`Kembali`='"+kembali.getDate().toString()+"',`Alamat`='"+Alamat.getText()+"',`Status`='"+status.getText()+"' WHERE Nomer ="+Nomer;
          
       
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "sukses",JOptionPane.INFORMATION_MESSAGE);
               selectData();
           }else{
               JOptionPane.showMessageDialog(this, "Gagal diupdate", "sukses",JOptionPane.WARNING_MESSAGE);
           }}        // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kolom[] = {"Nomer","Nama","Jenis","Judul","Pinjam","Kembali","Alamat", "Status"};
          DefaultTableModel dtm= new DefaultTableModel(null,kolom);
          String SQL = "SELECT * FROM tb_buku Where "+kategori.getSelectedItem()+"='"+txtsearch.getText()+"'";
         Alamat.setText(SQL);
          ResultSet rs = KoneksiDB.executeQuery(SQL);
          try{
              while(rs.next()){
              String Nomer = rs.getString(1);
              String Nama = rs.getString(2);
              String Jenis = rs.getString(3);
              String Judul = rs.getString(4);
              String Pinjam = rs.getString(5);
              String Kembali= rs.getString(6);
              String Alamat = rs.getString(7);
              String Status = rs.getString(8);
              String data[]={Nomer,Nama,Jenis,Judul,Pinjam,Kembali,Alamat,Status};
              dtm.addRow(data);
              }
          }catch (SQLException ex){
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Tidak ada data ditemukan");
          
       }
          tblData.setModel(dtm);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    
    public void selectData(){
          String kolom[] = {"Nomer","Nama","Jenis","Judul","Pinjam","Kembali","Alamat", "Status"};
          DefaultTableModel dtm= new DefaultTableModel(null,kolom);
          String SQL = "SELECT * FROM tb_buku";
          ResultSet rs = KoneksiDB.executeQuery(SQL);
          try{
              while(rs.next()){
              String Nomer = rs.getString(1);
              String Nama = rs.getString(2);
              String Jenis = rs.getString(3);
              String Judul = rs.getString(4);
              String Pinjam = rs.getString(5);
              String Kembali= rs.getString(6);
              String Alamat = rs.getString(7);
              String Status = rs.getString(8);
              String data[]={Nomer,Nama,Jenis,Judul,Pinjam,Kembali,Alamat,Status};
              dtm.addRow(data);
              }
          }catch (SQLException ex){
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
       }
          tblData.setModel(dtm);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> kategori;
    private com.toedter.calendar.JDateChooser kembali;
    private javax.swing.JLabel logo;
    private com.toedter.calendar.JDateChooser pinjam;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private javax.swing.JLabel status;
    private javax.swing.JTable tblData;
    private javax.swing.JLabel tulisan;
    private javax.swing.JTextField txtNomer;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
